[package]
name = "blindbid"
version = "0.1.0"
authors = ["kev <kevtheappdev@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
merlin = "1.0.1"
rand = "0.6"
subtle = "2"
curve25519-dalek = { version = "1.0.1", features = ["serde"] }
libc = "0.2"
lazy_static = "1.2.0"

[dependencies.bulletproofs]
git = "https://gitlab.dusk.network/kev/bp"
branch = "master"
features = ["yoloproofs"]

[lib]
crate-type = ["staticlib"]

[profile.release]
panic = 'abort'
# lto = true
incremental = true
# codegen-units = 1
